CREATE TABLE beerndonuts_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    beer_id INTEGER
        REFERENCES beerndonuts_beers(id) ON DELETE CASCADE NOT NULL
);
