DROP TYPE IF EXISTS style;
CREATE TYPE style AS ENUM (
    'Belgian Ale',
    'Blonde Ale',
    'Cider',
    'Coffee Porter',
    'Cream Ale'
    'India Pale Ale'
    'IPA'
    'NEIPA'
    'Pale Ale'
    'Pilsner'
    'Porter'
    'Russian Imperial Stout'
    'Saison'
    'Stout '
    'Sour'
);

CREATE TABLE IF NOT EXISTS beerndonuts_beer (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    beer_type style NOT NULL,
    tasting_notes TEXT NOT NULL,
)

CREATE TABLE IF NOT EXISTS beerndonuts_comments (

)